# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "chaowang11"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: False
publish_wechat: False

keywords:
    "Super-Resolution":
        filters: ["SR", "Super-Resolution", "Super Resolution"]
    "Image-Super-Resolution":
        filters: ["SISR", "Image Super Resolution"]
    "Video-Super-Resolution":
        filters: ["VSR", "Video Super Resolution"]
    "Text Erasing":
        filters: ["Text Erasing"]
    "Video Decaptioning":
        filters: ["Video Decaptioning","Video Colorization"]
    "Transformer":
        filters: ["Transformer"]
    "Image Inpainting":
        filters: ["Image Inpainting"]
    "Video Inpainting":
        filters: ["Video Inpainting"]